server:
  port: 8083

spring:
  kafka:
    consumer:
      bootstrap-servers: "[::1]:9092, [::1]:9094, [::1]:9096"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: weather-data-events
      properties:
        spring:
          json:
            trusted: true
  mail:
    host: smtp.mail.ru
    port: 587
    username: eljan.najafov02@mail.ru
    password: ${MAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: notification-service